### ISSUE TITLE
Use `BigInt` to represent Scheme numbers

### ISSUE THREAD

**Issue by acieroid** [softwarelanguageslab/maf#16]
The `gambit/compiler.scm` benchmarks contains literal numbers such as: `9223372036854775808`, which obviously do not fit into an `Int`.
This is throwing an error in the parsing phase, but will require changing `IntLattice` to use `BigInt` rather than simply `Int`.

**Comment by jevdplas** [comment]
Closed in ecc3b8fa077dc0d25ac4e6cc182fc2777e190e19.
