### ISSUE TITLE
Use TailCalls in Concrete Scheme Interpreter

### ISSUE THREAD

**Issue by jevdplas** [softwarelanguageslab/maf#5]
The concrete Scheme interpreter is currently written in a recursive style. This however causes stackoverflow errors on some benchmarks, meaning they cannot be used for testing.

**Comment by jevdplas** [comment]
To support `call-with-current-continuation`, the Scheme interpreter will have to be written in a CPS style.

**Comment by noahvanes** [comment]
Issue closed. See #18 for call/cc support.
